services:
  db:
    image: postgres:14
    container_name: biblioteka_service
    environment:
      POSTGRES_DB: biblioteka_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteka
    command: ["gunicorn", "--bind", "0.0.0.0:12345", "app:app"]
    volumes:
      - .:/biblioteka
    ports:
      - "12345:12345"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: biblioteka_db
      DB_USER: admin
      DB_PASSWORD: admin

volumes:
  postgres_data:
